### ISSUE TITLE
Method to compare stability / different versions of binning over time

### ISSUE THREAD

**Issue by AlexBrussee** [guillermo-navas-palencia/guillermo-navas-palencia#1]
Hi Guillermo,
When updating a model that uses optbinning it would be helpful if it is possible to compare previous models in order to test stability. For example are certain category labels switching to another bin? Is there already something like this in place? 
Kind regards,
Alex Brussee

**Comment by guillermo-navas-palencia** [comment]
Sorry, this is not the correct repo for creating OptBinning issues. Please re-open it there.
